name: MinecraftCommerce
description: An in-game shop plugin with real money
author: Tim van Dijkhuizen
version: "1.2.5"
api-version: 1.13
main: nl.timvandijkhuizen.commerce.Commerce
depend: [SpigotUtils]

commands:
   commerce:
      description: Manage Minecraft Commerce
      aliases: [shop]
      usage: /commerce