name: CustomPayments
description: Custom payments - An in-game shop plugin
author: Tim van Dijkhuizen
version: "1.0.0"
api-version: 1.13
main: nl.timvandijkhuizen.custompayments.CustomPayments

commands:
   custompayments:
      description: Manage custom payments
      aliases: [cp, shop]
      usage: /custompayments