name: Commerce
description: Commerce - An in-game shop plugin
author: Tim van Dijkhuizen
version: "1.0.0"
api-version: 1.13
main: nl.timvandijkhuizen.commerce.Commerce

commands:
   commerce:
      description: Manage Commerce
      aliases: [shop]
      usage: /commerce